version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot-admin
    restart: unless-stopped
    ports:
      - "3000:3000"  # Panel admin
      - "8080:8080"  # API/Webhook (optionnel)
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/bot_config.db
    networks:
      - bot-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: telegram-bot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./uploads:/var/www/uploads:ro
    networks:
      - bot-network
    depends_on:
      - telegram-bot

networks:
  bot-network:
    driver: bridge

volumes:
  bot_data:
    driver: local