name = "telegram-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# Configuration D1
[[d1_databases]]
binding = "DB"
database_name = "telegram-bot-db"
database_id = "YOUR_DATABASE_ID" # À remplacer par votre ID

# Variables d'environnement
[vars]
# Les variables sensibles doivent être définies via wrangler secret
# wrangler secret put BOT_TOKEN
# wrangler secret put ADMIN_ID

# Routes (optionnel)
# route = "bot.yourdomain.com/*"

# Configuration pour le développement local
[dev]
port = 8787
local_protocol = "http"

# Limites et configuration
[limits]
cpu_ms = 50

[build]
command = "npm install"

# Pour les webhooks Telegram
[triggers]
crons = []